library(RODBC)
library(mgcv)

AFSC=odbcConnect("AFSC","sbarb","sbarb$1011")

## Survey Age Data

Age=sqlQuery(AFSC, "SELECT RACEBASE.SPECIMEN.REGION,
  TO_CHAR(RACEBASE.HAUL.START_TIME, 'yyyy') AS YEAR,
  RACEBASE.SPECIMEN.CRUISE,
  RACEBASE.HAUL.VESSEL,
  RACEBASE.SPECIMEN.HAUL,
  RACEBASE.SPECIMEN.SPECIES_CODE,
  RACEBASE.SPECIMEN.LENGTH,
  RACEBASE.SPECIMEN.SEX,
  RACEBASE.SPECIMEN.WEIGHT,
  RACEBASE.SPECIMEN.MATURITY,
  RACEBASE.SPECIMEN.AGE,
  RACEBASE.HAUL.END_LONGITUDE,
  RACEBASE.HAUL.HAUL_TYPE,
  RACEBASE.HAUL.PERFORMANCE,
  RACEBASE.SPECIMEN.SPECIMEN_SAMPLE_TYPE,
  RACEBASE.SPECIMEN.SPECIMENID,
  RACEBASE.SPECIMEN.BIOSTRATUM
FROM RACEBASE.SPECIMEN
INNER JOIN RACEBASE.HAUL
ON RACEBASE.SPECIMEN.HAULJOIN                 = RACEBASE.HAUL.HAULJOIN
AND RACEBASE.HAUL.CRUISEJOIN                  = RACEBASE.SPECIMEN.CRUISEJOIN
WHERE RACEBASE.SPECIMEN.REGION                = 'AI'
AND RACEBASE.SPECIMEN.SPECIES_CODE            = 21740
AND RACEBASE.HAUL.HAUL_TYPE                   = 3
AND RACEBASE.HAUL.PERFORMANCE                >= 0
AND TO_CHAR(RACEBASE.HAUL.START_TIME, 'yyyy') > 1977
ORDER BY TO_CHAR(RACEBASE.HAUL.START_TIME, 'yyyy')")

Age_w<-subset(Age,Age$END_LONGITUDE > 0 | Age$END_LONGITUDE < -170)
Age_10<-subset(Age,Age$YEAR==2010)
Age_10w<-subset(Age_w,Age_w$YEAR==2010)

Age_w<-subset(Age_w,is.na(Age_w$AGE)==F)
Age_w$AGE1<-Age_w$AGE
Age_w$AGE1[Age_w$AGE1>=15]=15
Age_w$END_LONG<-Age_w$END_LONGITUDE
Age_w$END_LONG[Age_w$END_LONGITUDE<0]<- -Age_w$END_LONGITUDE[Age_w$END_LONGITUDE<0]
Age_w$END_LONG[Age_w$END_LONGITUDE>0]<- Age_w$END_LONGITUDE[Age_w$END_LONGITUDE>0]+ (180-Age_w$END_LONGITUDE[Age_w$END_LONGITUDE>0])

AGE<-aggregate(list(FREQ=Age_w$LENGTH),by=list(LENGTH=round(Age_w$LENGTH/10,-1),AGE=Age_w$AGE1,YEAR=Age_w$YEAR),FUN=length)


years<-unique(AGE$YEAR)


GRID<-expand.grid(YEAR=years,LENGTH=seq(10,max(AGE$LENGTH),10))
AGE1<-merge(GRID,AGE,all=T)
AGE1$FREQ[is.na(AGE1$FREQ)==T]=0

Total_A<-aggregate(list(Total=AGE1$FREQ),by=list(YEAR=AGE1$YEAR,LENGTH=AGE1$LENGTH),FUN=sum)

Total_B<-merge(AGE1,Total_A,all=T)
Total_B$Prob<-Total_B$FREQ/Total_B$Total
Total_B$Prob[Total_B$LENGTH==10&is.na(Total_B$Prob)==T]<-1.0
Total_B$AGE[Total_B$LENGTH==10&is.na(Total_B$AGE)==T]<-1.0

Total_B[410,]<- c(1980,0,1,1,0,1)
Total_B[411,]<- c(1983,0,1,1,0,1)
Total_B[412,]<- c(1986,0,1,1,0,1)
Total_B[413,]<- c(1991,0,1,1,0,1)
Total_B[414,]<- c(1994,0,1,1,0,1)
Total_B[415,]<- c(1997,0,1,1,0,1)
Total_B[416,]<- c(2000,0,1,1,0,1)
Total_B[417,]<- c(2004,0,1,1,0,1)
Total_B[418,]<- c(2006,0,1,1,0,1)
Total_B[419,]<- c(2004,90,15,1,0,1)

Total_B[121,]<- c(1986,80,14 ,1,0,1)
Total_B[123,]<- c(1991,20,1,1,0,1)
Total_B[84,]<- c(1983,80,14,1,0,1)
Total_B[2,]<- c(1980,20,1,1,0,1)
Total_B<-subset(Total_B,is.na(Total_B$AGE)==F)

Total_B<- Total_B[order(Total_B$YEAR,Total_B$LENGTH),]


##Length Data

Length=sqlQuery(AFSC,"SELECT RACEBASE.LENGTH.REGION,
  TO_CHAR(RACEBASE.HAUL.START_TIME, 'yyyy') AS YEAR,
  RACEBASE.LENGTH.CRUISE,
  RACEBASE.LENGTH.VESSEL,
  RACEBASE.LENGTH.HAUL,
  RACEBASE.LENGTH.SPECIES_CODE,
  RACEBASE.LENGTH.SEX,
  RACEBASE.LENGTH.LENGTH,
  RACEBASE.LENGTH.FREQUENCY,
  RACEBASE.HAUL.END_LONGITUDE,
  RACEBASE.HAUL.GEAR,
  RACEBASE.HAUL.STRATUM,
  RACEBASE.HAUL.HAUL_TYPE
FROM RACEBASE.LENGTH
INNER JOIN RACEBASE.HAUL
ON RACEBASE.LENGTH.CRUISEJOIN                 = RACEBASE.HAUL.CRUISEJOIN
AND RACEBASE.LENGTH.HAULJOIN                  = RACEBASE.HAUL.HAULJOIN
WHERE RACEBASE.LENGTH.REGION                  = 'AI'
AND RACEBASE.LENGTH.SPECIES_CODE              = 21740
AND TO_CHAR(RACEBASE.HAUL.START_TIME, 'yyyy') >= 1980
AND RACEBASE.HAUL.HAUL_TYPE                   = 3 ")


Length_w<-subset(Length,Length$END_LONGITUDE > 0 | Length$END_LONGITUDE < -170)
Length_w<-subset(Length_w,Length_w$YEAR!=1982)
Length_w<-subset(Length_w,Length_w$YEAR!=2010)


LENGTH=(data.frame(aggregate(list(FREQ=Length_w$FREQUENCY),by=list(LENGTH=Length_w$LENGTH/10,YEAR=Length_w$YEAR),FUN=sum)))
Total_L<-aggregate(list(Total=LENGTH$FREQ),by=list(YEAR=LENGTH$YEAR),FUN=sum)
Total_LB<-merge(LENGTH,Total_L,all=T)


## Survey WEIGHT at Age data

test<-gam(log(WEIGHT)~as.factor(YEAR)+s(LENGTH),gamma=1.4,data=Age_w)
new_data<-subset(Age_w,Age_w$YEAR==1980)
new_data$YEAR=1983
Age_w$WEIGHT[Age_w$YEAR==1980]<-exp(predict(test,newdata=new_data))


Weight<-subset(Age_w,is.na(Age_w$WEIGHT)==F)
WEIGHT<-aggregate(list(WEIGHT=Weight$WEIGHT),by=list(AGE=Weight$AGE1,YEAR=Weight$YEAR),FUN=mean)
grid=expand.grid(YEAR=sort(unique(WEIGHT$YEAR)),AGE=c(min(Age_w$AGE1):15))
WEIGHT_A<-merge(grid,WEIGHT,all=T)
test<-gam(log(WEIGHT)~as.factor(YEAR)+s(AGE,by=as.factor(YEAR)),gamma=1.4,data=subset(WEIGHT_A,is.na(WEIGHT_A$AGE)==F))
WEIGHT_A$pred<-exp(predict(test,newdata=WEIGHT_A))
WEIGHT_A$WEIGHT2<-WEIGHT_A$WEIGHT
WEIGHT_A$WEIGHT2[is.na(WEIGHT_A$WEIGHT2)==T]<-WEIGHT_A$pred[is.na(WEIGHT_A$WEIGHT2)==T]

GRID<-expand.grid(YEAR=c(1978:2011),AGE=c(1:15))
WEIGHT_B<-merge(GRID,WEIGHT_A,all=T)

WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==1978]= WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==1980]
WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==1979]= WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==1980]

WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==1981]= aggregate(WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==1980|WEIGHT_B$YEAR==1983],by=list(WEIGHT_B$AGE[WEIGHT_B$YEAR==1980|WEIGHT_B$YEAR==1983]),FUN=mean)$x
WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==1982]= aggregate(WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==1980|WEIGHT_B$YEAR==1983],by=list(WEIGHT_B$AGE[WEIGHT_B$YEAR==1980|WEIGHT_B$YEAR==1983]),FUN=mean)$x

WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==1984]= aggregate(WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==1983|WEIGHT_B$YEAR==1986],by=list(WEIGHT_B$AGE[WEIGHT_B$YEAR==1983|WEIGHT_B$YEAR==1986]),FUN=mean)$x
WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==1985]= aggregate(WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==1983|WEIGHT_B$YEAR==1986],by=list(WEIGHT_B$AGE[WEIGHT_B$YEAR==1983|WEIGHT_B$YEAR==1986]),FUN=mean)$x

WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==1987]= aggregate(WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==1986|WEIGHT_B$YEAR==1991],by=list(WEIGHT_B$AGE[WEIGHT_B$YEAR==1986|WEIGHT_B$YEAR==1991]),FUN=mean)$x
WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==1988]= aggregate(WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==1986|WEIGHT_B$YEAR==1991],by=list(WEIGHT_B$AGE[WEIGHT_B$YEAR==1986|WEIGHT_B$YEAR==1991]),FUN=mean)$x
WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==1989]= aggregate(WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==1986|WEIGHT_B$YEAR==1991],by=list(WEIGHT_B$AGE[WEIGHT_B$YEAR==1986|WEIGHT_B$YEAR==1991]),FUN=mean)$x
WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==1990]= aggregate(WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==1986|WEIGHT_B$YEAR==1991],by=list(WEIGHT_B$AGE[WEIGHT_B$YEAR==1986|WEIGHT_B$YEAR==1991]),FUN=mean)$x

WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==1992]= aggregate(WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==1991|WEIGHT_B$YEAR==1994],by=list(WEIGHT_B$AGE[WEIGHT_B$YEAR==1991|WEIGHT_B$YEAR==1994]),FUN=mean)$x
WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==1993]= aggregate(WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==1991|WEIGHT_B$YEAR==1994],by=list(WEIGHT_B$AGE[WEIGHT_B$YEAR==1991|WEIGHT_B$YEAR==1994]),FUN=mean)$x

WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==1995]= aggregate(WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==1994|WEIGHT_B$YEAR==1997],by=list(WEIGHT_B$AGE[WEIGHT_B$YEAR==1994|WEIGHT_B$YEAR==1997]),FUN=mean)$x
WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==1996]= aggregate(WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==1994|WEIGHT_B$YEAR==1997],by=list(WEIGHT_B$AGE[WEIGHT_B$YEAR==1994|WEIGHT_B$YEAR==1997]),FUN=mean)$x

WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==1998]= aggregate(WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==1997|WEIGHT_B$YEAR==2000],by=list(WEIGHT_B$AGE[WEIGHT_B$YEAR==1997|WEIGHT_B$YEAR==2000]),FUN=mean)$x
WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==1999]= aggregate(WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==1997|WEIGHT_B$YEAR==2000],by=list(WEIGHT_B$AGE[WEIGHT_B$YEAR==1997|WEIGHT_B$YEAR==2000]),FUN=mean)$x

WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==2001]= aggregate(WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==2000|WEIGHT_B$YEAR==2002],by=list(WEIGHT_B$AGE[WEIGHT_B$YEAR==2000|WEIGHT_B$YEAR==2002]),FUN=mean)$x

WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==2003]= aggregate(WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==2004|WEIGHT_B$YEAR==2002],by=list(WEIGHT_B$AGE[WEIGHT_B$YEAR==2002|WEIGHT_B$YEAR==2004]),FUN=mean)$x

WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==2005]= aggregate(WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==2006|WEIGHT_B$YEAR==2004],by=list(WEIGHT_B$AGE[WEIGHT_B$YEAR==2004|WEIGHT_B$YEAR==2006]),FUN=mean)$x

WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==2007]= WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==2006]
WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==2008]= WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==2006]
WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==2009]= WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==2006]
WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==2010]= WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==2006]
WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==2011]= WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==2006]

S_AGE_WEIGHT<-data.frame(matrix(ncol=15,nrow=length(unique(WEIGHT_B$YEAR))))
names(S_AGE_WEIGHT)<-c("YEAR","A2","A3" ,"A4","A5","A6","A7","A8","A9","A10","A11","A12","A13","A14","A15")
S_AGE_WEIGHT$YEAR<-c(1978:2011)

Years1<-c(1978:2011)
for( i in 1:length(Years1)){
S_AGE_WEIGHT[i,2:15]<-WEIGHT_B$WEIGHT2[WEIGHT_B$YEAR==Years1[i]][2:15]
}


## SUrvey Biomass Data

BIOMASS=sqlQuery(AFSC,"SELECT AI.BIOMASS_INPFC.SURVEY,
  AI.BIOMASS_INPFC.YEAR,
  AI.BIOMASS_INPFC.SUMMARY_AREA,
  AI.BIOMASS_INPFC.SPECIES_CODE,
  AI.BIOMASS_INPFC.AREA_BIOMASS,
  AI.BIOMASS_INPFC.BIOMASS_VAR,
  AI.BIOMASS_INPFC.AREA_POP,
  AI.BIOMASS_INPFC.POP_VAR
FROM AI.BIOMASS_INPFC
WHERE AI.BIOMASS_INPFC.SUMMARY_AREA != 799
AND AI.BIOMASS_INPFC.SPECIES_CODE    = 21740
ORDER BY AI.BIOMASS_INPFC.YEAR,
  AI.BIOMASS_INPFC.SUMMARY_AREA ")

BIO<-data.frame(aggregate(list(BIO=BIOMASS$AREA_BIOMASS,POP=BIOMASS$AREA_POP),by=list(YEAR=BIOMASS$YEAR),FUN=sum)  )

VAR<-data.frame(aggregate(list(BIO=BIOMASS$BIOMASS_VAR,POP=BIOMASS$POP_VAR),by=list(YEAR=BIOMASS$YEAR),FUN=sum)  )

survey_biomass=t(data.frame(BIO=BIO$BIO,B_STDEV=sqrt(VAR$BIO)))
BIO<-subset(BIO,YEAR!=2010)
Total_WB<-merge(Total_LB,BIO,all=T)
Total_WB$Prob<-Total_WB$FREQ/Total_WB$Total
Total_WB$C_LENGTH<-Total_WB$Prob*Total_WB$POP

CATCH_LENGTH<-aggregate(list(C_LENGTH=Total_WB$C_LENGTH),by=list(LENGTH=round(Total_WB$LENGTH,-1)YEAR=Total_WB$YEAR),FUN=sum)

## Output for Survey Catch at age
Total_test<-merge(Total_B,CATCH_LENGTH,all=T)
Total_test$CATCH_AGE<-Total_test$Prob*Total_test$C_LENGTH
Total<-subset(Total_test,is.na(Total_test$C_LENGTH)==F)
remove(Total_test)


FINAL_CATCH_AGE=aggregate(list(CATCH_AGE=Total$CATCH_AGE),by=list(AGE=Total$AGE,YEAR=Total$YEAR),FUN=sum)
FINAL_TOTAL<-aggregate(list(Total=FINAL_CATCH_AGE$CATCH_AGE),by=list(YEAR=FINAL_CATCH_AGE$YEAR),FUN=sum)

FINAL_CATCH_AGE=merge(FINAL_CATCH_AGE,FINAL_TOTAL)
FINAL_CATCH_AGE$PROP<-FINAL_CATCH_AGE$CATCH_AGE/FINAL_CATCH_AGE$Total


S_CATCH_PROP<-data.frame(matrix(ncol=15,nrow=length(unique(FINAL_CATCH_AGE$YEAR))))
names(S_CATCH_PROP)<-c("YEAR","A2","A3" ,"A4","A5","A6","A7","A8","A9","A10","A11","A12","A13","A14","A15")
Years1<-unique(AGE$YEAR)
S_CATCH_PROP$YEAR<-Years1

for( i in 1:length(Years1)){
S_CATCH_PROP[i,2:15]<-FINAL_CATCH_AGE$PROP[FINAL_CATCH_AGE$YEAR==Years1[i]][2:15]
}
S_CATCH_PROP[2,15]<-0
S_CATCH_PROP[3,15]<-0


##Survey Data
survey_biomass
S_CATCH_PROP
S_AGE_WEIGHT

