
get_Sage<-function(region="'AI'",species=21740,sy=1977,GEAR=172){     ##GOA and AI BT = 172, BS = 44 pollock - 21740 Greenland turbot=10115  AI BT = 160

  test<-paste("SELECT RACEBASE.SPECIMEN.REGION,\n ",
        "TO_CHAR(RACEBASE.HAUL.START_TIME, 'yyyy') AS YEAR,\n ",
        "RACEBASE.SPECIMEN.CRUISE,\n ",
        "RACEBASE.HAUL.VESSEL,\n ",
        "RACEBASE.SPECIMEN.HAUL,\n ",
        "RACEBASE.SPECIMEN.SPECIES_CODE,\n ",
        "RACEBASE.SPECIMEN.LENGTH,\n ",
        "RACEBASE.SPECIMEN.SEX,\n ",
        "RACEBASE.SPECIMEN.WEIGHT,\n ",
        "RACEBASE.SPECIMEN.MATURITY,\n ",
        "RACEBASE.SPECIMEN.AGE,\n ",
        "RACEBASE.HAUL.END_LONGITUDE,\n ",
        "RACEBASE.HAUL.HAUL_TYPE,\n ",
        "RACEBASE.HAUL.PERFORMANCE,\n ",
        "RACEBASE.SPECIMEN.SPECIMEN_SAMPLE_TYPE,\n ",
        "RACEBASE.SPECIMEN.SPECIMENID,\n ",
        "RACEBASE.SPECIMEN.BIOSTRATUM\n ",
        "FROM RACEBASE.SPECIMEN\n ",
        "INNER JOIN RACEBASE.HAUL\n ",
        "ON RACEBASE.SPECIMEN.HAULJOIN = RACEBASE.HAUL.HAULJOIN\n ",
        "AND RACEBASE.HAUL.CRUISEJOIN = RACEBASE.SPECIMEN.CRUISEJOIN\n ",
        "WHERE RACEBASE.SPECIMEN.REGION = ",region,"\n",
        "AND RACEBASE.SPECIMEN.SPECIES_CODE = ", species,"\n",
        "AND RACEBASE.HAUL.HAUL_TYPE = 3\n",
        "AND RACEBASE.HAUL.PERFORMANCE >= 0\n",
        "AND TO_CHAR(RACEBASE.HAUL.START_TIME, 'yyyy') >",sy,"\n",
        "AND RACEBASE.HAUL.GEAR = ",GEAR,"\n",
        "ORDER BY TO_CHAR(RACEBASE.HAUL.START_TIME, 'yyyy')",sep="")

     Age=sqlQuery(AFSC,test)
     Age
}