get_Slength<-function(region="'AI'",species=21740,sy=1977,GEAR=172){


  test<-paste("SELECT RACEBASE.LENGTH.REGION,\n ",
    "TO_CHAR(RACEBASE.HAUL.START_TIME, 'yyyy') AS YEAR,\n ",
   "RACEBASE.LENGTH.CRUISE,\n ",
   "RACEBASE.LENGTH.VESSEL,\n ",
   "RACEBASE.LENGTH.HAUL,\n ",
   "RACEBASE.LENGTH.SPECIES_CODE,\n ",
   "RACEBASE.LENGTH.SEX,\n ",
   "RACEBASE.LENGTH.LENGTH,\n ",
   "RACEBASE.LENGTH.FREQUENCY,\n ",
   "RACEBASE.HAUL.END_LONGITUDE,\n ",
   "RACEBASE.HAUL.GEAR,\n ",
   "RACEBASE.HAUL.STRATUM,\n ",
   "RACEBASE.HAUL.HAUL_TYPE\n ",
  "FROM RACEBASE.LENGTH\n ",
  "INNER JOIN RACEBASE.HAUL\n ",
  "ON RACEBASE.LENGTH.CRUISEJOIN = RACEBASE.HAUL.CRUISEJOIN\n ",
  "AND RACEBASE.LENGTH.HAULJOIN = RACEBASE.HAUL.HAULJOIN\n ",
  "WHERE RACEBASE.LENGTH.REGION = ",region,"\n",
  "AND RACEBASE.LENGTH.SPECIES_CODE = ",species,"\n",
  "AND TO_CHAR(RACEBASE.HAUL.START_TIME,'yyyy') >= ", sy,"\n",
  "AND RACEBASE.HAUL.HAUL_TYPE = 3\n",
  "AND RACEBASE.HAUL.GEAR = ",GEAR,sep="")

 Length=sqlQuery(AFSC,test)
 Length
}



