get_SHAUL<-function(region="'AI'",sy=2002,GEAR=172){


  test<-paste("SELECT RACEBASE.HAUL.REGION,\n ",
    "TO_CHAR(RACEBASE.HAUL.START_TIME, 'yyyy') AS YEAR,\n ",
   "TO_CHAR(RACEBASE.HAUL.START_TIME,'HH24') AS TIME,\n ",
   "RACEBASE.HAUL.CRUISE,\n ",
   "RACEBASE.HAUL.VESSEL,\n ",
   "RACEBASE.HAUL.HAUL,\n ",
   "RACEBASE.HAUL.END_LONGITUDE,\n ",
   "RACEBASE.HAUL.END_LATITUDE, \n ",
   "RACEBASE.HAUL.GEAR,\n ",
   "RACEBASE.HAUL.STRATUM,\n ",
   "RACEBASE.HAUL.BOTTOM_DEPTH,\n ",
   "RACEBASE.HAUL.GEAR_TEMPERATURE\n ",
   "FROM RACEBASE.HAUL \n ",
  "WHERE RACEBASE.HAUL.REGION = ",region," \n",
  "AND TO_CHAR(RACEBASE.HAUL.START_TIME,'yyyy') >= ", sy," \n",
  "AND RACEBASE.HAUL.HAUL_TYPE = 3 \n",
  "AND RACEBASE.HAUL.GEAR = ",GEAR,sep="")

 haul=sqlQuery(AFSC,test)
 haul
}



