library(RODBC)
library(mgcv)
setwd("D:/_mymods/AMAK/examples/AI_Pollock/R_functions")


  AFSC=odbcConnect("AFSC")
  source("get_Sage.r")
  source("get_AIbiom.r")
  source("get_Slength.r")
  source("find_AL.r")
  source("AGE_LENGTH.r")
  source("SWEIGHT.r")
  source("get_Fage.r")
  source("get_Sage.r")
  source("get_Flength.r")
  source("get_Dage.r")
  source("get_Dlength.r")
  source("write_dat.r")
  source("get_FSS.r")
  source("get_DSS.r")
  source("FWEIGHT.r")
  source("get_all_data.r")

 test=get_all_data(fyear=2014, species=21740,region="'AI'",MINAGE=100, filename="ai14.dat",WRITE=T)
